### ISSUE TITLE
ST2205 USB picture frame fails

### ISSUE THREAD

**Issue by setop** [gphoto/gphoto2#130]
Hi,

I'm trying to upload a picture on a photo frame brand Telefunken, model DPF 2401.
It seems to be a sort of ST2205 device.

I don't know if I can tweak some parameters to make it work.

[my-logfile.log](https://github.com/gphoto/gphoto2/files/1899402/my-logfile.log)

**Comment by jwrdegoede** [comment]
Hi,

This is causes by:

https://github.com/gphoto/libgphoto2/commit/b06e5d1216b775d0f6cdee97d82d30fcd46912e9#diff-428a377b8f18aeeae312f0fb75b1e257

Which added a:

	C_PARAMS (!port);

Instead of a:

	C_PARAMS (port);

That commit is quite old, so it seems not a lot of people are
actually using st2205 picture frames, that is not that surprising
since shortly after I wrote the driver all manufacturers switches
to the ax203 chipset which is even cheaper :)

Marcus, I'm a bit swamped at the moment, can you fix this please?

setop, if you can build libgphoto2 from source, then you can try
the fix by editing libgphoto2_port/usbdiskdirect/linux.c and
changing line 315 from:

	C_PARAMS (!port);

To:

	C_PARAMS (port);

Building a version with that change should fix this.

Regards,

Hans

**Comment by msmeissn** [comment]
sure, thanks :)
