### ISSUE TITLE
Configuration not working with Canon EOS M50

### ISSUE THREAD

**Issue by ramsii** [gphoto/gphoto2#167]
Hi! I can capture photos using --capture-image or --capture-preview. So far so good...

But no configuration seems to work:
set-config manualfocusdrive=6
set-config-index manualfocusdrive=6
set-config-index "/main/actions/manualfocusdrive"=6
set-config-index /main/actions/manualfocusdrive=6

Neither the "CURRENT value using get-config nor the focus of the camera/photo it self does change....

gphoto2: {/root} /> get-config manualfocusdrive 
Label: Drive Canon DSLR Manual focus
Readonly: 0
Type: RADIO
Current: None
Choice: 0 Near 1
Choice: 1 Near 2
Choice: 2 Near 3
Choice: 3 None
Choice: 4 Far 1
Choice: 5 Far 2
Choice: 6 Far 3
END

What am'I doing wrong?

other commands do work e.g.
-set-config datetimeutc=`date +%s`

Here the list of the running versions:
gphoto2 2.5.20.1 gcc, popt(m), exif, no cdk, no aa, no jpeg, no readline
libgphoto2 2.5.20.1 all camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0 iolibs: disk ptpip serial usb usbdiskdirect usbscsi, gcc, ltdl, USB, serial without locking

Here the full debug log: [[temp.txt](https://github.com/gphoto/gphoto2/files/2552170/temp.txt)
]

BR, Ramsi

BTW: I also posted this a few days ago in https://sourceforge.net/p/gphoto/bugs/1037/ but it looks like there's not much going on there...

**Comment by msmeissn** [comment]
the manualfocusdrive is an one-shot action, it does not stick.

But there are problems with setting values like iso, aperture etc on the EOS M series which I have not yet figured out.

**Comment by robjasey** [comment]
Were you able to figure out how to set the aperture and shutter on the EOS M cameras? I am trying this with an M50 Mark II and find I can set the ISO but not the shutter or aperture.

**Comment by robjasey** [comment]
Ignore my comment. Rookie mistake (camera was set to P!). M50 Mark II is working for shutter, ISO, Aperture, white balance drive mode , image target, battery level, format; all the things I need. Shutter count not found , but not critical.

**Comment by msmeissn** [comment]
Good to hear the 50Mark 2 can do configuration!

Still considering original M50 is not able to.

**Comment by grelle** [comment]
I'm also having issues with multiple remote mounted M50's that several times during the day fails to capture the image due to what I have managed to understand "Perhaps no focus?". It seems as if they do break mechanically due to this because it continues to try to focus over and over again, we have had to replace and repair a couple of them already.

It seems that the camera tries to autofocus even though I have tested multiple solutions to force it to use manual focus.

I did put my hope into "set-config manualfocusdrive=6" during the capture event but it does not seem to help.

**Comment by theonejrm** [comment]
Hi there, 
while my project switching to linux, I actually get stuck at the same point. I want to use my M50 as webcam for meetings, but I can not set the value for Camera Outpu to PC. It just stays at MOBILE2. I haven't tried the other settings yet, but I guess it's a bug in general. 
Did finally someone of you found solution, workaround or anything?

**Comment by grelle** [comment]
I was able to solve this by using something with trigger immediate and release and then wait for event "downloaded file" or something similiar. This bypassed the autofocus, for me it is important however to be sure that focus is set to manual on the camera, this setting seemes to survive reboots of the camera. _I did solve this by using the camera at home in my lab because trying to troubleshoot remote was a pain._

I'm unable to reach my remote right now where I have the command stored, will get back to you asap.

**Comment by theonejrm** [comment]
Great to hear that there is hope to get it work somehow! I'm looking forward to the command to test it. Thanks

**Comment by grelle** [comment]
> Great to hear that there is hope to get it work somehow! I'm looking forward to the command to test it. Thanks

Yes, I'm not sure you are experiencing the same issue as I had. My issue was clearly that the camera tried to autofocus in and environment without focuspoints (pitch black). Anyway, below command effectively bypasses autofocus when capturing images (not filming):

`--set-config eosremoterelease=Immediate --set-config eosremoterelease='Release Full' --wait-event-and-download=FILEADDED `
