### ISSUE TITLE
Error -110 On 1300D

### ISSUE THREAD

**Issue by AllanJake** [gphoto/gphoto2#308]
**Describe the bug**

"gphoto2 --trigger-capture" works fine when first connecting the camera but upon triggering a second time I get *** Error (-110: 'I/O in progress') *** 

**Name the camera**
Canon EOS 1300D

**libgphoto2 and gphoto2 version**
GPhoto2: 2.5.23.1
libgphoto2: 2.5.22

I have attatched the output of logfile

[my-logfile.txt](https://github.com/gphoto/gphoto2/files/4530792/my-logfile.txt)

thanks

**Comment by msmeissn** [comment]
the logfile ends quite early, as if gphoto2 crashes or so. I this the logfile of the Error 110?

**Comment by AllanJake** [comment]
I fully reinstalled gphoto2 today, run the command again and the output of this log file seems longer. Unsure if it is still crashing or not but I still have the same error where the first trigger-capture works perfectly but all subsequent attempts give Error 110

**Versions:**
libgphoto2: 2.5.24.1
gphoto2: 2.4.23.1

[logfile.txt](https://github.com/gphoto/gphoto2/files/4561050/logfile.txt)

thanks

**Comment by msmeissn** [comment]
The camera reports "CameraStatus 1" which usually means its busy.

Are you capturing to SDRAM or to Card?   (capturetarget property)

If you capture to SDRAM you must also do some --wait-event-and-download=2s or   similar timerange to fetch the image from SDRAM.

Otherwise the camera will report busy as it can only have some images in SDRAM.

**Comment by AllanJake** [comment]
Thanks! I set the capturetarget to use the card rather than the SDRAM and it fixed the issue
