### ISSUE TITLE
gPhoto2 - LiveView Streaming | Delay and FPS

### ISSUE THREAD

**Issue by sakibnaz** [gphoto/gphoto2#321]
Hi there.

I testing LiveView Streaming with my Canon 6D and VLC player using the below command:

gphoto2 --set-config viewfinder=1

gphoto2 --capture-movie --stdout | ffmpeg -re -i pipe:0 -listen 1 -f mjpeg http://10.10.10.253:8080/feed.mjpg

![image](https://user-images.githubusercontent.com/6670151/81733159-5e472880-94b3-11ea-8229-6fd3b7900a8a.png)

The streaming works but I am getting a big delay of around 4-5 sec and the stream video also not smooth.

Anyone advise please, how to make the stream more real-time and increase the FPS?

Also one question ... I want to change the settings like Focus, ISO, Shutter etc when its in Streaming. Is it possible?

Thanks.

**Comment by msmeissn** [comment]
the buffering is likely gphoto2 unrelated, so check if some no buffer options for ffmpeg help:

https://stackoverflow.com/questions/16658873/how-to-minimize-the-delay-in-a-live-streaming-with-ffmpeg

changing settings is hard. you would need to write your own program that does the srteaming and then set values. ... Look at examples/preview.c  for instance, or similar. But it will be some effort.

**Comment by fgervais** [comment]
@sakibnaz can I ask for an update on this? Were you able to fix the latency?

**Comment by sakibnaz** [comment]
Hi, still I am not able to reduce the delay. It's around 2-3 sec with
FFMPEG.

Thanks.

**Comment by szotsaki** [comment]
As I observed ffmpeg is only one side of the equation, you also have to pay attention to the player software. If you use mpv, you need to apply the low-latency profile when you are experimenting; like this:
```
mpv --profile=low-latency av://v4l2:/dev/video0
```
With [OBS](https://obsproject.com) this is automatic since that software's main purpose it to broadcast (with low-latency).

**Comment by felixniemeyer** [comment]
I still have this issue in 2024.

I once was able to get real time video from my Canon EOS 600D using gphoto2. 
Now, the video lags behind around 1 second making it unusable for video calls for example. 

I'm wondering what has changed since 2021 where remember it working just fine... Did I mess around with the magicklantern custom firmware on the Camera? Did something about gphoto2 or ffmpeg change?
 
Would be super happy if we could resolve this...

**Comment by andredsnogueira** [comment]
@felixniemeyer did you find any solution? I am also encountering the same issue.

**Comment by felixniemeyer** [comment]
@andredsnogueira After trying a couple of different applications (jitsi in chrome and firefox and obs-studio) the latency suddenly became better (around 0.1s now, which is sufficient) without me being aware of what caused the change!
Maybe try various applications? 
Maybe it takes one to request a real time stream... this is wild guessing
I think that's all I can tell you.
