### ISSUE TITLE
FULL PC error on CANON 7d Mark 1

### ISSUE THREAD

**Issue by reddai75** [gphoto/gphoto2#330]
I'm seeing this problem on my Canon 7D (Mark 1): the camera reports "FULL PC" error when octolapse (a plug for octoprint) calls for consecutive gphoto2-calls in a short space of time.
The message on the 7D-LCD-display is "Full PC". Once it's in that state, nothing works, and the error is usually only cleared by power cycling the camera or disconnecting it from my Raspberry. I couldn't find much about this issue on internet, only few people reporting the same, without a solution.
Calling gphoto in, say, lessthan 3 second intervals, is very likely to cause the problem; with
intervals over 10s I haven't seen any error...
Do you have any advice or a way to circumvent the issue ?
**libgphoto2 and gphoto2 version**

gphoto2 2.5.20

Steps to reproduce the behavior: it happens randomly, quite often but not always when there are consecutive calls

**Comment by msmeissn** [comment]
Can you update to a new libgphoto2 version?

Full PC happens because:
- we tell the camera how much space in bytes is left on the PC side (yes, weird enough).
- If the camera has taken that many pictures, it will report PC Full.


I fixed this issue in libgphoto2 2.5.22 I think, so please upgrade and try to reproduce.

**Comment by reddai75** [comment]
Outstanding! will do and keep you posted! 

many thanks!

**Comment by msmeissn** [comment]
assuming fixed

**Comment by johnenriquez** [comment]
unfortunately running into the same issuewith the same camera - and it likewise is hard to reproduce consistently, as doing test snapshot work fine but there is no pattern to when in the sequence `FULL PC` will lock up the camera. and confirming that running `gphoto2 -v` on the pi 3b+ gives me `gphoto2 2.5.20`, `libgphoto2 2.5.22`. let me know what else I can provide to help!

**Comment by reddai75** [comment]
I'm sorry I could not test it more I'm busy with a lot of work and I had to
take a break from my hobbies.
Please let me know if you manage, I'll probably test it again around
December



Il Sab 19 Set 2020, 06:54 John Enriquez <notifications@github.com> ha
scritto:

**Comment by msmeissn** [comment]
can you check with gphoto2 --version   what versions are there?

are you capturing very large RAW files?

**Comment by msmeissn** [comment]
if exchanging the camera to one of the same model helps, it might be camera related. especially if it happens only after a long while and is not cured by powercycle.


( PC FULL is happening if the camera captures more content than we claim to be able to store. but might also be reporting this in other cases.)

We claim enough memory before all capture attempts since 2.5.22 libgphoto2.
